# Generated by Django 2.2 on 2020-08-16 22:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_format', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='scientific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=40)),
                ('note', models.TextField(default='備註')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Specise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specise_name', models.CharField(max_length=20)),
                ('note', models.TextField(default='備註')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='gene_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_length', models.PositiveIntegerField()),
                ('sequence', models.CharField(max_length=10000)),
                ('annotation', models.CharField(max_length=50)),
                ('description', models.TextField(default='暫無說明')),
                ('date', models.DateField(auto_now=True)),
                ('f_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.data_type', verbose_name='序列格式')),
                ('n_scientific', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.scientific', verbose_name='學名')),
                ('n_specise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.Specise', verbose_name='物種')),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
