# Generated by Django 2.2 on 2020-08-16 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20200817_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_type',
            name='seq_format',
            field=models.CharField(max_length=8),
        ),
    ]
