# Generated by Django 3.1 on 2020-09-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_auto_20200817_0650'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_search_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_word', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reference_summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(blank=True, max_length=30, null=True)),
                ('organism_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('chinese_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('genus', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('species_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('gram_stain', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('top_type', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('source', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('key_word', models.TextField(blank=True, default='', null=True)),
                ('sample_type', models.TextField(blank=True, default='', null=True)),
                ('Halos_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('taxid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('species_taxid', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, default='', null=True)),
                ('reference1', models.TextField(blank=True, null=True)),
                ('reference2', models.TextField(blank=True, null=True)),
                ('reference3', models.TextField(blank=True, null=True)),
                ('reference4', models.TextField(blank=True, null=True)),
                ('reference5', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('data_source', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('data_status', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
    ]
