# Generated by Django 3.1 on 2020-09-16 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_db_search_log_reference_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reference_summary',
            old_name='orgranism_name',
            new_name='organism_name',
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='data_source',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='data_status',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
