# Generated by Django 3.1 on 2020-08-19 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_reference_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference_summary',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='Halos_id',
            field=models.CharField(default='暫無說明', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='chinese_name',
            field=models.CharField(default='暫無說明', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='data_source',
            field=models.CharField(default='unknow', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='data_status',
            field=models.CharField(default='unknow', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='db_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='genus',
            field=models.CharField(default='unkown genus', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='gram_stain',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='orgranism_name',
            field=models.CharField(default='暫無說明', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='source',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='species_name',
            field=models.CharField(default='unkown species', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='taxid',
            field=models.CharField(default='暫無說明', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='top_type',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
