# Generated by Django 3.1 on 2020-08-19 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_auto_20200819_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_summary',
            name='Halos_id',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='chinese_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='key_word',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='orgranism_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='species_name',
            field=models.CharField(default='unkown species', max_length=100),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='taxid',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
