# Generated by Django 3.1 on 2020-08-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_auto_20200819_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_summary',
            name='genus',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='species_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
