# Generated by Django 3.1 on 2020-08-19 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_auto_20200819_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_summary',
            name='reference2',
            field=models.TextField(default='no reference', null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='reference3',
            field=models.TextField(default='no reference', null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='reference4',
            field=models.TextField(default='no reference', null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='reference5',
            field=models.TextField(default='no reference', null=True),
        ),
    ]
