# Generated by Django 3.1 on 2020-08-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_auto_20200819_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_summary',
            name='Description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='Halos_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='chinese_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='data_source',
            field=models.CharField(blank=True, default='unknow', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='data_status',
            field=models.CharField(blank=True, default='unknow', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='db_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='genus',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='gram_stain',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='key_word',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='orgranism_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='reference1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='reference2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='reference3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='reference4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='reference5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='source',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='species_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='taxid',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reference_summary',
            name='top_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
