# Generated by Django 3.1 on 2020-08-19 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_auto_20200819_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference_summary',
            name='species_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
