# Generated by Django 3.1 on 2020-09-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_auto_20200908_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_search_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_word', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=20)),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
    ]
