# Generated by Django 3.1 on 2020-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_auto_20200911_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='reference_summary',
            name='sample_type',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
